#!/bin/sh

# IOS - projekt 1
# Daša Nosková - xnosko05

POSIXLY_CORRECT=yes

num_of_parameters=$#
param=1
num_of_filters=0
only_one_c=none
filter_or_command="false"


get_ip () 
{
	echo "$1" | cut -d ' ' -f1 | sort 
}

get_date_in() #preformatuje datum zo vstupu
{
	echo "$1" | awk -v FS=[\-\ \:] -v OFS='' '{print $1,$2,$3,$4,$5,$6}'
}

get_date_file() #skopiruje datum zo suboru na zaciatok riadku a preformatuje ho
{
	echo "$1" | sort | awk '{print $4,$0}' | awk '{	
				sub("Jan","01",$1);
				sub("Feb","02",$1);
				sub("Mar","03",$1);
				sub("Apr","04",$1);
				sub("May","05",$1);
				sub("Jun","06",$1);
				sub("Jul","07",$1);
				sub("Aug","08",$1);
				sub("Sep","09",$1);
				sub("Oct","10",$1);
				sub("Nov","11",$1);
				sub("Dec","12",$1);
				sub (/[[]/,"");
				for (i=0; i < 2; i++) 
					sub ("/"," ");
				sub (":"," ");
				for (i=0; i < 2; i++) 
					sub (":","");
				print $0}' | awk '{
					printf"%s%s%s%s",$3,$2,$1,$4
					$1=$2=$3=$4="";
					print $0
				}' | sort -k1 
}


#####		SPRACOVANIE ARGUMENTOV 		#####
while [ "$param" -le "$num_of_parameters" ]; do
	case "${1}" in 
		"-a")
			a="${1}"
			a_DATETIME="${2}"
			if echo "$a_DATETIME" | grep -q -E '^[0-9]{4}(-[0-9]{2}){2} ([0-9]{2}:){2}[0-9]{2}$' ; then 
				shift 2
			else
				echo "Zly format datumu."
				exit 1
			fi
			#shift 2
			num_of_filters=$((num_of_filters+1))
			filter_or_command="true"
		;;
		"-b") 
			b="${1}"
			b_DATETIME="${2}"
			if echo "$b_DATETIME" | grep -q -E '^[0-9]{4}(-[0-9]{2}){2} ([0-9]{2}:){2}[0-9]{2}$' ; then 
				shift 2
			else
				echo "Zly format datumu."
				exit 1
			fi
			num_of_filters=$((num_of_filters+1))
			filter_or_command="true"
		;;
		"-ip") 
			ip="${1}"
			IPADDR="${2}" 
			if echo "$IPADDR" | grep -q -E '^([0-9]{1,3}\.){3}[0-9]{1,3}$' ; then #IPv4
				shift 2
			elif echo "$IPADDR" | grep -q -E '^([0-9a-fA-F]{0,4}:){1,7}[0-9a-fA-F]{0,4}$'; then #IPv6
				shift 2
			else
				echo "Zly format IP."
				exit 1
			fi
			num_of_filters=$((num_of_filters+1))
			filter_or_command="true"
		;;
		"-uri") 
			uri="${1}"
			URI="${2}" #regularny vyraz
			shift 2
			num_of_filters=$((num_of_filters+1))
			filter_or_command="true"
		;;
		"list-ip" | "list-hosts" | "list-uri" | "hist-ip" | "hist-load")
			#pridat podmienku if command one then echo chyba exit
			if [ "$only_one_c" = "one" ]; then 
				echo "Zadanych vela prikazov."
				exit 1;
			fi 
			command="${1}"
			shift
			only_one_c="one"
			filter_or_command="true"
		;;
		*\.*)
			#file=`cat ${1}`
			#echo "$file"
			#shift
		;;
		*)
			echo "Filter/prikaz nenajdeny."
			exit 1;
		;;
	esac
	param=$((param+1))
done

######################################		SPRACOVANIE suborov 	##############################
if [ $# -eq 0 ]; then ##ak nedostane subor  
	FILE=`while read -r line; do 
		echo "$line"
    	done`
    	file="$file""$FILE"
fi

while [ $# -gt 0 ]; do #spracuje subor
	FILE="${1}"
	shift
	if [ -f "$FILE" ]; then 
		#skontroluje ci je subor typu gz ak ano tak ho unzipne, nacita subor
		FILE=`(echo "$FILE" | grep -Eq '.*\.gz') && gunzip -cd "$FILE" || cat "$FILE" | while read -r line; do  #otvori subor
		echo "$line"
		done`
    	file="$file""$FILE" #ulozi vsetky subory do jednej premmenej 
    else
		echo "Subor neexistuje." 
		exit 1;
	fi
done
	#####		FILTER 		#####
		if [ -n "$a" ]; then #skontroluje ci je premenna a prazdna
			a_DATETIME=`get_date_in "$a_DATETIME"` #premeni vstupny datum na velke cislo
			file=`get_date_file "$file" | awk -v DATE="$a_DATETIME" '{if($1>DATE) {$1="";print $0}}' | sed 's/ //1'` #porovna velke cislo a vypise iba vacsie
		fi	

		if [ -n "$b" ]; then #vypise iba mensie
			b_DATETIME=`get_date_in "$b_DATETIME"`
			file=`get_date_file "$file" | awk -v DATE="$b_DATETIME" '{if($1<DATE) {$1="";print $0}}' | sed 's/ //1'` 
		fi

		if [ -n "$ip" ]; then #vypise iba riadky vyhovujuce zadanej IP 
			file=`echo "$file" | grep -e "$IPADDR"`
		fi

		if [ -n "$uri" ]; then #vypise iba riadky vyhovujuce zadanemu vyrazu
			file=`echo "$file" | grep -e "$URI"`
		fi

	###### 			PRIKAZ 			######
	case "${command}" in
		list-ip) #vypise ip adresy z prveho stlpca
			file=`get_ip "$file" | uniq`
		;;

		list-hosts) 
			file=`get_ip "$file" | uniq | xargs -n1 host -i | cut -d ' ' -f5`
			
		;;

		list-uri) #vypise uri, stlpec 7 zacinajuci /
			file=`echo "$file" | cut -d ' ' -f7 | grep -E ^/ | sort | uniq`
		;;

		hist-ip) #pocetnost IP adries
			file=`get_ip "$file" | uniq -c | sort -n -r | awk -v OFS='' '{
				printf ("%s%s%s%s%s%s%s"),$2," ","(",$1,")",":"," ";
				for (i=0; i < $1; i++) 
					printf("#");
					printf("\n")
			}'`
		;;

		hist-load) #preformatuje datum a urobit pocetnost
			file=`echo "$file" | awk '{print $4}' | awk '{
				sub("Jan","01");
				sub("Feb","02");
				sub("Mar","03");
				sub("Apr","04");
				sub("May","05");
				sub("Jun","06");
				sub("Jul","07");
				sub("Aug","08");
				sub("Sep","09");
				sub("Oct","10");
				sub("Nov","11");
				sub("Dec","12");
			}1' | awk -v FS=[\:\/'['] -v OFS='' '{
			      print $4,"-",$3,"-",$2," ",$5,":","00"
				}' | sort -n | uniq -c | awk -v OFS=' ' -v ORS="" '{
				print $2,$3,"("$1")"":",""
				for (i=0; i < $1; i++) 
					printf("#");
					printf("\n")
			}'`
		;;

	esac

	echo "$file"



			
